backend:
  name: git-gateway
  branch: main

media_folder: "site/static/images/uploads" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Article" # Used in the UI, ie.: "New Post"
    folder: "site/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Type", name: "type", widget: "select", options: ["post", "featured"], default: ["post"]}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Catégories", name: "categories", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/a-propos.md"
        label: "À propos"
        name: "apropos"
        fields:
          - {label: Titre, name: title, widget: string}
          - {label: "Date", name: "date", widget: "datetime"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}          
      - file: "site/content/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: Titre, name: title, widget: string}
          - {label: "Date", name: "date", widget: "datetime"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image", name: "image", widget: "image", required: false}
          - {label: "Layout", name: "layout", widget: "select", options: ["contact"], default: ["contact"]}
          - {label: "Body", name: "body", widget: "markdown"}
